name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: blackwall.fdemb.me
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build app files
        run: bun run build

      - name: Build server binary
        run: bun build ./scripts/server.ts --compile --target=bun-linux-x64 --bytecode --minify --sourcemap

      - name: Build migrator binary 
        run: bun build ./scripts/migrator.ts --compile --target=bun-linux-x64 --bytecode --minify --sourcemap

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy app files
        run: |
          rsync -avz --no-perms --chmod=u=rwX,g=rX,o= --delete \
            -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            --exclude database \
            ./dist \
            ./server \
            ./migrator \
            ./src/db/migrations \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}
